0,0 +1,7 @@
# Copyright (c) 2022-2024, NVIDIA CORPORATION & AFFILIATES, All rights reserved.
#
# This work is licensed under a Creative Commons
# Attribution-NonCommercial-ShareAlike 4.0 International License.

[env]
module = "src.envs.brachiation_env"
class = "BrachiationEnv"